version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: node:18
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
    command: sh -c "npm install && npm run dev"
    depends_on:
      - postgres
    shm_size: '1gb'

  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
